version: '3'

networks:
  sofanet:

services:
  webserver:
      container_name: webserver
      image: apache/airflow:slim-latest-python3.11
      entrypoint: ['/opt/airflow/script/entrypoint.sh']
      command: webserver
      depends_on:
        - postgres
      environment:
        - LOAD_EX=n
        - EXECUTOR=LocalExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - AIRFLOW__WEBSERVER__SECRET_KEY=my_secret_key
        - GCP_PROJECT_ID=foot-analyse
        - BQ_DATASET_ID=foot_data
        - BQ_TABLE_ID=football_results
        - BUCKET_ID=football_lake
        - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/credentials/credentials.json
        - PROXIES_PATH=/opt/airflow/proxies/valid_proxies.txt
      logging:
        options:
          max-size: 10m
          max-file: "3"
      volumes:
        - ./dags:/opt/airflow/dags
        - ./scripts/entrypoint.sh:/opt/airflow/script/entrypoint.sh
        - ./credentials/:/opt/airflow/credentials/
        - ./requirements.txt:/opt/airflow/requirements.txt
        - ./logs/:/opt/airflow/logs
        - ./proxies/valid_proxies.txt:/opt/airflow/proxies/valid_proxies.txt
      ports:
        - "8080:8080"
      healthcheck:
        test: ['CMD-SHELL', "[ -f /opt/airflow/airflow-webserver.pid ]"]
        interval: 90s
        timeout: 90s
        retries: 3
      networks:
        - sofanet

  scheduler:
      container_name: scheduler
      image: apache/airflow:slim-latest-python3.11
      depends_on:
        webserver:
          condition: service_healthy
      volumes:
        - ./dags:/opt/airflow/dags
        - ./scripts/entrypoint.sh:/opt/airflow/script/entrypoint.sh
        - ./credentials/:/opt/airflow/credentials/
        - ./requirements.txt:/opt/airflow/requirements.txt
        - ./logs/:/opt/airflow/logs
        - ./proxies/valid_proxies.txt:/opt/airflow/proxies/valid_proxies.txt
      environment:
        - LOAD_EX=n
        - EXECUTOR=LocalExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - AIRFLOW__WEBSERVER__SECRET_KEY=my_secret_key
        - GCP_PROJECT_ID=foot-analyse
        - BQ_DATASET_ID=foot_data
        - BQ_TABLE_ID=football_results
        - BUCKET_ID=football_lake
        - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/credentials/credentials.json
        - PROXIES_PATH=/opt/airflow/proxies/valid_proxies.txt
      entrypoint: ['/opt/airflow/script/entrypoint.sh']
      
      command: scheduler
      networks:
        - sofanet

  postgres:
      image: postgres:14.10-bullseye
      environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
      logging:
        options:
          max-size: 11m
          max-file: "3"
      networks:
        - sofanet
