version: '3'

networks:
  sscore:

services:
  webserver:
      image: apache/airflow:slim-latest-python3.11
      entrypoint: ['/opt/airflow/script/entrypoint.sh']
      command: webserver
      depends_on:
        - postgres
      environment:
        - LOAD_EX=n
        - EXECUTOR=Sequential
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - AIRFLOW_WEBSERVER_SECRET_KEY=this_is_a_very_secured_key
        - GCP_PROJECT_ID=foot-analyse
        - BQ_DATASET_ID=foot_data
        - BQ_TABLE_ID=football_results
        - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/credentials/credentials.json
      logging:
        options:
          max-size: 10m
          max-file: "3"
      volumes:
        - ./dags:/opt/airflow/dags
        - ./scripts/entrypoint.sh:/opt/airflow/script/entrypoint.sh
        - ./credentials/:/opt/airflow/credentials/
        - ./requirements.txt:/opt/airflow/requirements.txt
      ports:
        - "8080:8080"
      healthcheck:
        test: ['CMD-SHELL', "[ -f /opt/airflow/airflow-webserver.pid ]"]
        interval: 160s
        timeout: 160s
        retries: 3
      networks:
        - sscore

  scheduler:
      image: apache/airflow:slim-latest-python3.11
      depends_on:
        webserver:
          condition: service_healthy
      volumes:
        - ./dags:/opt/airflow/dags
        - ./scripts/entrypoint.sh:/opt/airflow/script/entrypoint.sh
        - ./credentials/:/opt/airflow/credentials/
        - ./requirements.txt:/opt/airflow/requirements.txt
      environment:
        - LOAD_EX=n
        - EXECUTOR=Sequential
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - AIRFLOW_WEBSERVER_SECRET_KEY=this_is_a_very_secured_key
        - GCP_PROJECT_ID=foot-analyse
        - BQ_DATASET_ID=foot_data
        - BQ_TABLE_ID=football_results
        - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/credentials/credentials.json
      entrypoint: ['/opt/airflow/script/entrypoint.sh']
      command: scheduler
      networks:
        - sscore

  postgres:
      image: postgres:14.10-bullseye
      environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
      logging:
        options:
          max-size: 10m
          max-file: "3"
      networks:
        - sscore
